---

mock_with: ':rspec'

.gitlab-ci.yml:
  delete: true
appveyor.yml:
  delete: true

.travis.yml:
  user: MiamiOH
  secure: "TQgcTTSTL5UPRrKxbEdY8G6Kn7kGZVTn3tZOOM4YshYN40XMst3upOn15QHZAJ7IcyG0oWj9ijftGWF4hsTPohGYkqCezbAj2ZyOmSQk7fzP+slYw7R9ivvMJ+lWgGz0eMN0+Z8bUmJMglrGOHnE41vrvbB6rugV0lfW4Cfzna38m9DMtZv2pAek/XfBaExnGBEq7CQXUPYIrBdHIN2nkBuwBRTl8koprHgMN6S6VR785mcI4Y154Q7mJC1mARBWWEnVaKEOhBGfMIrYSy98hf05JKuV5R8ljAY9ibqW2cLq78HnWHYp8ExQ2u/e+YtdGhrGTDzqJQN/exWFrBi0BDRM8QSAe8lneixqc4qAg3ExHGJHrJctPaC6ul8Xhg4R9cURITbGQR0VKjhz9hPJKcF96tALqPXfsGZSkNZr0mUyoYi4nmOhqFye6C/4JF8gYtmiZH4o10K3RcEEcVv6BiR6vO+M6j6nDq/MA3iU/FMY77LLfttnZYjHfXwBH9ZuPDWqmd9xJr6Oiz8qUiDUF+BWnof0ukU+lw4DVIhpuenWmznN+gKrICGAruoKL4eBMCYoggunOQ/ZONVaIXK3ZRW/SeXKk5arvML/xDdR1n7ikAoZ9q2+xRnOcINBstkm1XQRSASIMzG0wzRL/v4J8kGflrDGSJn0JyBLqPVYMcc="
Gemfile:
  required:
    ':development':
      - gem: travis

Rakefile:
  default_disabled_lint_checks:
  - security_package_pinned_version
  - 140chars
